field: 32712cfb-8a4d-4f62-ae43-0e6ed9c8714f
fieldLayouts:
  e61da655-d6be-4828-b5ce-29a5566a1d45:
    tabs:
      -
        elements:
          -
            fieldUid: d3a87be6-1fd8-41b4-a78c-1d74ea0f71f2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d3a87be6-1fd8-41b4-a78c-1d74ea0f71f2:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:ea6d6b66-2a4a-411b-a022-a62793429d7c'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1bc7b595-8601-44b4-b427-0e927919a810'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:ea6d6b66-2a4a-411b-a022-a62793429d7c'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 5
