contentColumnType: text
fieldGroup: 2c6828c5-46bf-4ad6-b752-26413ff16eaa
handle: companyGlobalVat
instructions: ''
name: 'Num√©ro TVA principal'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
