contentColumnType: string
fieldGroup: 4ac25835-7a0d-46f7-8c12-822cb727b4f2
handle: videoBanner
instructions: ''
name: 'Vid√©o Banner'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:1bc7b595-8601-44b4-b427-0e927919a810'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1bc7b595-8601-44b4-b427-0e927919a810'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:1bc7b595-8601-44b4-b427-0e927919a810'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
